const express = require("express");
const router = express.Router()
const upload = require("../middleware/multer")
const {addUser} = require("../api/user/userController")
const {admin,adminLogin} = require("../config/seed")
const {registerRenter,loginRenter,getAllRenter} = require("../api/renter/renterController")
const {registerHirer, loginHirer,getAllHirers,changePassword} = require("../api/hierer/hiererController")
const {addCar,getCars,getCarById,updateCar,deleteCar} = require("../api/car/carController")
const {addVehicle,getVehicles} = require("../api/vechile/vechileController")
const {addBrand,getBrands, getBrandById, updateBrand, deleteBrand } = require("../api/brand/brandController")
const {createBooking,getAllBooking,getBookingById,deleteBooking,updateBookingStatus} = require("../api/booking/bookingController")

router.post("/createbooking",createBooking)
router.post("/getallbooking",getAllBooking)
router.post("/getbookingbyid",getBookingById)
router.post("/deletebooking",deleteBooking)
router.post("/updatebookingstatus",updateBookingStatus)
router.post("/addbrand",addBrand)
router.post("/getbrand",getBrands)
router.post("/getbrandbyid",getBrandById)
router.post("/updatebrand",updateBrand)
router.post("/deletebrand",deleteBrand)
router.post("/addvehicle",addVehicle)
router.post("/getvehicle",getVehicles)
router.post("/adduser",addUser)
router.post("/admin",admin)
router.post("/login",adminLogin)
router.post("/registerRenter",registerRenter)
router.post("/loginRenter",loginRenter)
router.post("/getallrenter",getAllRenter)
router.post("/registerHirer",registerHirer)
router.post("/loginHirer",loginHirer)
router.post("/getallhirer",getAllHirers)
router.post("/changepassword",changePassword)
router.post("/addcar",upload.single("image"),addCar)
router.post("/getcar",getCars)
router.post("/getcarbyid",getCarById)
router.post("/updatecar",upload.single("image"),updateCar)
router.post("/deletecar",deleteCar)

module.exports = router